# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Werror -pedantic  -Iinclude

# Final executable name
TARGET = tanks_game

# Platform detection
ifeq ($(OS),Windows_NT)
    RM = del /Q /F
    MKDIR_P = if not exist "$(subst /,\,$(dir $@))" mkdir "$(subst /,\,$(dir $@))"
    EXEC = $(TARGET).exe
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S),Darwin)
        RM = rm -rf
        MKDIR_P = mkdir -p $(dir $@)
        EXEC = $(TARGET)  # macOS: no .exe
    else
        RM = rm -rf
        MKDIR_P = mkdir -p $(dir $@)
        EXEC = $(TARGET)  # Linux or others
    endif
endif

# Source files
SRC = $(wildcard src/Common/*.cpp src/Core/*.cpp src/utils/*.cpp src/Algorithms/*.cpp src/Algorithms/Roles/*.cpp) main.cpp
OBJ = $(SRC:%.cpp=obj/%.o)

# Default target
all: $(EXEC)

# Link all object files
$(EXEC): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Compile source to object files
obj/%.o: %.cpp
	@$(MKDIR_P)
	$(CXX) $(CXXFLAGS) -c $< -o $@

.PHONY: all clean

# Clean target
clean:
ifeq ($(OS),Windows_NT)
	@if exist obj rmdir /S /Q obj
	@if exist $(TARGET).exe del /Q /F $(TARGET).exe
	@if exist $(TARGET) del /Q /F $(TARGET)
else
	$(RM) obj $(TARGET) $(TARGET).exe
endif
